CREATE TABLE IF NOT EXISTS `formatos_impresion` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `tipo_documento` VARCHAR(50) NOT NULL UNIQUE,
    `nombre_plantilla` VARCHAR(100) NOT NULL,
    `ancho_papel_mm` SMALLINT UNSIGNED NOT NULL DEFAULT 80,
    `cuerpo_html` LONGTEXT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
